api_key: null
cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$lhOfbg3eMo9/TIcgFOvlbuYTGJQBdTLU/ek3SiDOooJNrIktqfKr6
      roles:
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$SxD/z1xJN6C7G7ygeiCuDOR88ZFAMoky9nCm9JgACEuJiVbVV6/4a
      roles:
      - viewer
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
